# Generated by Django 2.1.1 on 2018-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0002_auto_20181127_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstance',
            name='number_no_votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songinstance',
            name='number_yes_votes',
            field=models.IntegerField(),
        ),
    ]
