# Generated by Django 2.1.2 on 2018-12-03 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HiveList', '0002_auto_20181127_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInstance',
            fields=[
                ('vote_instance_id', models.UUIDField(default=uuid.uuid4, help_text='unique ID for this particular Song Instance', primary_key=True, serialize=False)),
                ('vote', models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
                ('contributor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playlist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='songinstance',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='songinstance',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='songinstance',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='voteinstance',
            name='song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.SongInstance'),
        ),
    ]
