# Generated by Django 2.1.1 on 2018-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0003_auto_20181203_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstance',
            name='number_no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songinstance',
            name='number_yes_votes',
            field=models.IntegerField(default=0),
        ),
    ]
