# Generated by Django 2.1.2 on 2018-12-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0003_auto_20181203_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinstance',
            name='num_vote',
            field=models.IntegerField(default=0),
        ),
    ]
