# Generated by Django 2.1.1 on 2018-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0004_auto_20181203_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_creation_date',
            field=models.DateField(blank=True),
        ),
    ]
