# Generated by Django 2.1.1 on 2018-12-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0005_auto_20181205_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
