# Generated by Django 2.1.2 on 2018-12-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0005_auto_20181203_0247'),
        ('HiveList', '0004_auto_20181203_1533'),
    ]

    operations = [
    ]
