# Generated by Django 2.1.1 on 2018-12-05 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0006_auto_20181205_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
