# Generated by Django 2.1.2 on 2018-12-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0006_merge_20181204_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteinstance',
            name='contributor_id',
        ),
        migrations.RemoveField(
            model_name='voteinstance',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='voteinstance',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='num_vote',
        ),
        migrations.RemoveField(
            model_name='song',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='song',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='song',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='num_vote',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='vote_score',
        ),
        migrations.DeleteModel(
            name='VoteInstance',
        ),
    ]
