# Generated by Django 2.1.2 on 2018-12-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0007_auto_20181204_0253'),
        ('HiveList', '0007_auto_20181205_2054'),
    ]

    operations = [
    ]
