# Generated by Django 2.1.1 on 2018-11-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HiveList', '0025_playlist_playlist_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_creator_id',
            new_name='playlist_creator',
        ),
        migrations.AddField(
            model_name='contributors',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songinstance',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
