# Generated by Django 2.1.1 on 2018-11-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0026_auto_20181115_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_creator',
            new_name='playlist_creator_id',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='adder',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='adder',
        ),
    ]
