# Generated by Django 2.1.1 on 2018-11-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0027_auto_20181115_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'permissions': (('can_contribute', 'Contribute songs'),)},
        ),
    ]
