# Generated by Django 2.1.3 on 2018-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0027_auto_20181127_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_vote_time',
            field=models.DateField(auto_now=True),
        ),
    ]
