# Generated by Django 2.1.1 on 2018-11-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0027_auto_20181127_0226'),
        ('HiveList', '0026_auto_20181115_1815'),
    ]

    operations = [
    ]
