# Generated by Django 2.1.3 on 2018-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0028_playlist_playlist_vote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_vote_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
